### ISSUE TITLE
Set Ileana's permissions in team https://github.com/orgs/nmfs-openscapes/teams/2022-noaa-sefsc-fall-cohort

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#120]
@jules32 Where do I change permission and how:

Ileana does not yet have permission to make commit to https://github.com/nmfs-openscapes/2022-noaa-sefsc-fall. This may be because I created the repo and team manually instead of with kyber. 

Do I set her as Maintainer? In [repo](https://github.com/nmfs-openscapes/2022-noaa-sefsc-fall) or in [team](https://github.com/orgs/nmfs-openscapes/teams/2022-noaa-sefsc-fall-cohort)?

This also has me wondering if kyber is ready for me to make the remaining Cohort teams this week.

**Comment by jules32** [comment]
Hi! I had a look and then invited her to the [SEFSC repo](https://github.com/nmfs-openscapes/2022-noaa-sefsc-fall) > Settings > Collaborators as Admin. I think that's the best approach for all 4 of the repositories, if you'd like to do the same for the other 3

So that Ileana isn't unnecessarily spammed at this point we set access repo-by-repo rather than org level; I don't think this is a kyber thing so no worries there.

**Comment by stefaniebutland** [comment]
Thanks! IleanaF is now Admin on all 4 Cohort repos
