### ISSUE TITLE
DRAFT Call 4 digest [ NOAA-NMFS ]

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#28]
Hi @cclatterbuck , I hope the Trash Data Workshop went well! 

Today's NMFS Cohort was really awesome and we missed you. Do you still want to plan drafting out the digest, or would you like me to since you weren't there? If you do, you can see the notes in the cohort folder, and Anna's got a great template https://github.com/Openscapes/cohort-planning/issues/27

**Comment by jules32** [comment]
TODO Julie: Also add 3-month checkins

**Comment by cclatterbuck** [comment]
Hi @jules32 ! I can take care of this week's digest. I'll use Anna's template as a starting point and potentially get feedback from you during tomorrow's meetup. Thanks!

**Comment by cclatterbuck** [comment]
Hi All,

Thanks for a great fourth session last Friday. Thank you to Gavin, Andy, and Rachel for making this FDD cohort happen, and big thanks to all of the teams for contributions to conversations and notes throughout this Openscapes process. We loved hearing about your Pathways last week and are looking forward to continued conversations and momentum around how the NOAA community can do better science in less time - for future you, your teams, and your collaborators! 

A few things to wrap up:

1. **Feedback!** Openscapes improves with each cohort based on candid feedback. Please fill out this survey by Friday [ July 9 ]:
    * [Openscapes survey]( INSERT LINK ) for specific feedback on Openscapes

2. Invitation to an optional 3-month check-in call on [ January 24, 10-11am ET ] ; We will send a calendar invite now and a reminder email with light structure closer to the date. This will be a time for folks to share informal updates, reconnect, and ask questions.

3. We’ll draft a blog post in our [CohortCalls folder](https://drive.google.com/drive/u/2/folders/1Xx-G_9s6DGz4JduYQblJNuMMFaPgU7sb) later this week; we invite you to add comments or suggestions if you’re interested. 

4. Snail mail! Please email an address for your team to Julie so we can send stickers!

We are so grateful for your thoughtful engagement and impressed with your progress and pathway plans. We hope you continue to iterate your Seaside Chats with your research groups and we are happy to meet with your research groups during a Seaside Chat since not everyone from each team was able to make it to our last call. Please get in touch to schedule.

Please keep in touch on Slack and Twitter!

Cheers,

Anna & Julie


## Digest: Cohort Call 4 [ 2021-FDD ]

[CohortCalls folder](https://drive.google.com/drive/folders/1Xx-G_9s6DGz4JduYQblJNuMMFaPgU7sb?usp=sharing) - contains video recordings and completed agendas
[openscapes.github.io/2021-fdd](https://openscapes.github.io/2021-fdd) - Cohort webpage

**Goals:** Each team shared their pathway and we discussed how to keep momentum going forward.

**Themes** that came across through the final pathways shares:

- Lots of interest in investing time to developing documentation of onboarding/offboarding processes, codes of conduct, available datasets/data description guides, methodologies.
- There are challenges around if/how to share confidential data, or other people's data - and interest in continuing dialogue within the FDD community to find solutions.
- Collaboration is essential within teams and with external partners, but finding the right workflows and tools to do that well takes time and iteration. We're working on it! 
- Lots of actions and next steps, including increasing or refining use of GitHub (or other collaboration tools) in workflows, and continuing bi-weekly FDD Cohort calls, and alternating between share outs, co-working, office hours, etc. 

**Resources:**

- [PathwayShare Folder](https://drive.google.com/drive/u/2/folders/1j1nYc_FPgsfCm9XvLWvQBdcsCMZczHd8)
- Slide decks from past calls are available publicly from [openscapes.org/series](https://openscapes.github.io/series)
- “Graduation gift” - Openscapes badges by Allison Horst!
    * Download from here: [openscapes_hex_badge.png](https://github.com/Openscapes/how_we_work/blob/main/openscapes_hex_badge.png)
    * You can put it on your website, like the [Wood Lab](https://chelsealwood.com/research/) and the [Fay Lab](https://thefaylab.github.io/lab-manual/index.html)!

**A few lines from shared notes in the Agenda doc:**

- Thought a lot about code of conduct; need to be more clear about how to work with data, data access, acknowledging contributors across multiple institutions +1 +1 +1
- +1 to [Gavin’s onboarding document](https://thefaylab.github.io/lab-manual/index.html)
    * Julie ‘made’ us use a Creative Commons license for the lab manual so it’s there for stealing and modifying. Go nuts!
- How to not create a divide between GH/R/diff data users and non +1 +1 +1
- FDD Office Hours +1 +1 +1 +1 +1
    * Or co-working, or share outs
    * Keeping every 2 weeks timing - alternating co-working and more planned content (share your research using FDD to start)
    * Have space that allows for conversation of how these tools are actually used to do science. Continuing conversations about how we work is very valuable.

**Comment by jules32** [comment]
Thanks @cclatterbuck , this looks good to me! I'll work on the survey and other links, and can update after our seaside chat tomorrow too

**Comment by jules32** [comment]
Whoops ha I just realized this is a copy of FDD (that I hadn't read yet). Sounds good that you'll start here and then @eeholmes  and I will be able to review (sorry Eli, I've un-assigned you for now :)

**Comment by cclatterbuck** [comment]
To-do
[ ] fill in & edit brackets
[ ] test links


Hi All,

Thanks for a great fourth session last Friday. Thank you to [Eli] for making this NMFS cohort happen, to Emily Markowitz and Chanté Davis for their guest lectures, and big thanks to all of the teams for contributions to conversations and notes throughout this Openscapes process. We loved hearing about your Pathways last week and are looking forward to continued conversations and momentum around how the NMFS community can do better science in less time - for future you, your teams, and your collaborators! 

A few things to wrap up:

1. **Feedback!** Openscapes improves with each cohort based on candid feedback. Please fill out this survey by Friday [ July 9 ]:
    * [Openscapes survey]( INSERT LINK ) for specific feedback on Openscapes

2. Invitation to an optional 3-month check-in call on [ January 24, 10-11am ET ] ; We will send a calendar invite now and a reminder email with light structure closer to the date. This will be a time for folks to share informal updates, reconnect, and ask questions.

3. We’ll draft a blog post in our [CohortCalls folder](https://drive.google.com/drive/u/1/folders/1JgsXSY6EASG5wuczF-INs12O4QMC8xZn) later this week; we invite you to add comments or suggestions if you’re interested. 

4. Snail mail! Please email an address for your team to Julie so we can send stickers!

We are so grateful for your thoughtful engagement and impressed with your progress and pathway plans. We hope you continue to iterate your Seaside Chats with your research groups and we are happy to meet with your research groups during a Seaside Chat [since not everyone from each team was able to make it to our last call.] Please get in touch to schedule.

Please keep in touch on Slack and Twitter!

Cheers,

Eli, Corey, and Julie


## Digest: Cohort Call 4 [ 2021-NOAA-NMFS ]

[CohortCalls folder](https://drive.google.com/drive/u/1/folders/1JgsXSY6EASG5wuczF-INs12O4QMC8xZn) - contains video recordings and completed agendas
[openscapes.github.io/2021-noaa-nmfs](https://openscapes.github.io/2021-noaa-nmfs) - Cohort webpage

**Goals:** Each team shared their pathway and we discussed how to keep momentum going forward.

**Themes** that came across through the final pathways shares:

- Lots of interest in investing time to developing documentation of onboarding/offboarding processes, codes of conduct, available datasets/data description guides, methodologies.
- There are challenges around if/how to share confidential data, or other people's data. One option presented was to document where the data is from or use a simulated dataset & some of the steps to work with the data.
- Collaboration is essential within teams and with external partners, but onboarding people who are outside your Openscapes team remains a challenge -- some groups are doing well, but others still have questions and need time to do this. Some resources include [AFSC's onboarding document](https://afsc-gap-products.github.io/pages/onboarding) and using this [Github in NOAA & NMFS](https://github.com/Openscapes/2021-noaa-nmfs/wiki/1-GitHub-in-gov#github-in-noaa--nmfs) page in the wiki.
- The culture of engaging in good data practices requires dedicated time, including coworking times where data organization is specifically discussed.  

**Resources:**

- [PathwayShare Folder](https://drive.google.com/drive/folders/1JgsXSY6EASG5wuczF-INs12O4QMC8xZn?usp=sharing)
- Slide decks from past calls are available publicly from [openscapes.org/series](https://openscapes.github.io/series)
- “Graduation gift” - Openscapes badges by Allison Horst!
    * Download from here: [openscapes_hex_badge.png](https://github.com/Openscapes/how_we_work/blob/main/openscapes_hex_badge.png)
    * You can put it on your website, like the [Wood Lab](https://chelsealwood.com/research/) and the [Fay Lab](https://thefaylab.github.io/lab-manual/index.html)!

**A few lines from shared notes in the Agenda doc:**

-  time to learn and practice; buy-in from team members and time to get them up to speed (trained); coordination with team members and collaborators (it takes time to build relationships, communicate, etc) +1+1
- Getting everyone in the group to commit to the Pathway; taking the time to create the much needed documentation +1 +1 +1
- Maybe the NWFS has an “open science team” or some such to propose center-wide approaches to software platforms, project management, data management, workflows, styles, etc. (all the things we have been talking about in openscapes)? 
    * some of us within FRAM and SDM have discussed codifying bits of time in performance plans to dedicate to enterprise-level data services, and I think your idea of a “open science team” would fit nicely into that framework.
-  how do we ensure this momentum continues into tangible actions?  This has always been a challenge given everyone’s high workload.  Creating and developing lines of communications and platforms takes time and effort. To be successful we will need to have individuals to continue to spearhead these efforts to ensure momentum is not lost.

**Comment by cclatterbuck** [comment]
whoa, sorry for the confusion! I deleted the draft that was focused on FDD and commented a new one :) @jules32

**Comment by jules32** [comment]
Awesome thanks Corey!

**Comment by eeholmes** [comment]
Thanks for drafting, Corey! It's great! I added a few links for the NMFS R UG upcoming events and an invite link to the slack channel.

**Comment by jules32** [comment]
Thanks All! posted here: https://github.com/Openscapes/2021-noaa-nmfs/issues/37

**Comment by eeholmes** [comment]
> To-do
> - [x] fill in & edit brackets
> - [x] test links
> - [x] Julie initial review
> - [x] Eli sign-off
> - [x] Julie sign-off
> 
> Hi All,
> 
> Thanks for a great final session last Friday. Thank you to Eli, Eric and Helene for making this NMFS cohort happen, to Emily Markowitz and Chanté Davis for their guest lectures, and big thanks to all of the teams for contributions to conversations and notes throughout this Openscapes series. We loved hearing about your Pathways last week and are looking forward to continued conversations and momentum around how the NMFS community can do better science in less time - for future you, your teams, and your collaborators! 
> 
> A few things to wrap up:
> 
> 1. **Openscapes survey** - Eli will send this separately. We improve with each cohort based on candid feedback;  Please respond by Friday Nov 12
> 
> 2. **NMFS R UG upcoming events**
>     * Nov 16 9am PST [Lightning Talks on R Markdown for Scientific reports, manuscripts and presentations](https://calendar.google.com/event?action=TEMPLATE&tmeid=Mjc2OWIwM2k0OWRwNDNvamdvajExdXFqNGUgbm9hYS5nb3ZfNjByZm43bWw5cnBjaGw2M3ZzNGFmOW4wMThAZw&tmsrc=noaa.gov_60rfn7ml9rpchl63vs4af9n018%40group.calendar.google.com)
>     * [Sign up for the NMFS R UG to hear about events](https://docs.google.com/spreadsheets/d/1WwiGAf7Lmrx3sdrif3R-IhIJiXUIFBHydloixY6fWuo/edit#gid=0)
> 
> 3. **Continuing Cohort Calls** - We'll send calendar invites for our every-two-week calls, with the short-term plan of alternating these times as co-working and more scheduled share-outs. We'll invite the [NOAA NMFS Cohort](https://openscapes.github.io/2021-noaa-nmfs) as well; they've just finished their cohort too and we through we could combine forces and see what next steps emerge. Feb 4 can be our 3-month check-in to reassess. 
> 
> 4. **Blog post** - we'll draft this in our [CohortCalls folder](https://drive.google.com/drive/u/2/folders/1Xx-G_9s6DGz4JduYQblJNuMMFaPgU7sb) later this week; we invite you to add comments or suggestions if you’re interested. 
> 
> 5. **Snail mail!** Please Slack/email an address for your team to Julie (lowndes@nceas.ucsb.edu) so we can send stickers!
> 
> We are so grateful for your thoughtful engagement and impressed with your progress and pathway plans. We hope you continue to iterate your Seaside Chats with your research groups. Please keep in touch on Slack and Twitter!
> 
> Cheers,
> 
> Eli, Corey, and Julie
> 
> 
> ## Digest: Cohort Call 4 [ 2021-NOAA-NMFS ]
> 
> [CohortCalls folder](https://drive.google.com/drive/u/1/folders/1JgsXSY6EASG5wuczF-INs12O4QMC8xZn) - contains video recordings and completed agendas
> [openscapes.github.io/2021-noaa-nmfs](https://openscapes.github.io/2021-noaa-nmfs) - Cohort webpage
> https://github.com/nmfs-openscapes - NMFS Openscapes community going forward
> Join the Openscapes Slack group to stay connected with all the Openscapes cohorts [Click this invite link](https://join.slack.com/t/openscapes/shared_invite/zt-x64zr7ms-u51snmD3gdNllhHABePxfQ)
> 
> **Goals:** Each team shared their pathway and we discussed how to keep momentum going forward.
> 
> **Themes** that came across through the final pathways shares:
> 
> - Lots of interest in investing time to developing documentation of onboarding/offboarding processes, codes of conduct, available datasets/data description guides, methodologies.
> - Collaboration is essential within teams and with external partners, but onboarding people who are outside your Openscapes team remains a challenge -- some groups are doing well, but others still have questions and need time to do this. Some resources include [AFSC's onboarding document](https://afsc-gap-products.github.io/pages/onboarding) and using this [Github in NOAA & NMFS](https://github.com/Openscapes/2021-noaa-nmfs/wiki/1-GitHub-in-gov#github-in-noaa--nmfs) page in the wiki.
> - The culture of engaging in good data practices requires dedicated time, including coworking times where data organization is specifically discussed.  
> 
> **Resources:**
> 
> - [PathwayShare Folder](https://drive.google.com/drive/folders/1JgsXSY6EASG5wuczF-INs12O4QMC8xZn?usp=sharing)
> - Slide decks from past calls are available publicly from [openscapes.org/series](https://openscapes.github.io/series)
> - “Graduation gift” - Openscapes badges by Allison Horst!
>     * Download from here: [openscapes_hex_badge.png](https://github.com/Openscapes/how_we_work/blob/main/openscapes_hex_badge.png)
>     * You can put it on your website, like the [Wood Lab](https://chelsealwood.com/research/) and the [Fay Lab](https://thefaylab.github.io/lab-manual/index.html)!
> 
> **A few lines from shared notes in the Agenda doc:**
> 
> -  time to learn and practice; buy-in from team members and time to get them up to speed (trained); coordination with team members and collaborators (it takes time to build relationships, communicate, etc) +1+1
> - Getting everyone in the group to commit to the Pathway; taking the time to create the much needed documentation +1 +1 +1
> - Maybe the NMFS has an “open science team” or some such to propose center-wide approaches to software platforms, project management, data management, workflows, styles, etc. (all the things we have been talking about in Openscapes)? 
>     * some of us within FRAM and SDM have discussed codifying bits of time in performance plans to dedicate to enterprise-level data services, and I think your idea of a “open science team” would fit nicely into that framework.
> -  how do we ensure this momentum continues into tangible actions?  This has always been a challenge given everyone’s high workload.  Creating and developing lines of communications and platforms takes time and effort. To be successful we will need to have individuals to continue to spearhead these efforts to ensure momentum is not lost.
>
